# Generated by Django 4.2.1 on 2023-11-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False},
        ),
    ]
