# Generated by Django 4.2.1 on 2023-11-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
