# Generated by Django 4.2.1 on 2023-11-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_image',
            field=models.ImageField(blank=True, upload_to='clients/last_images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
