# Generated by Django 4.2.1 on 2023-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_client_phone_client_status_alter_client_is_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=16)),
                ('login', models.CharField(max_length=128)),
                ('parol', models.CharField(max_length=128)),
                ('is_enter', models.BooleanField(default=True)),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'camera',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='last_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
