# Generated by Django 4.2.7 on 2023-11-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='employees/')),
                ('last_image', models.ImageField(blank=True, upload_to='last_images/')),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_enter_time', models.DateTimeField(auto_now_add=True)),
                ('last_leave_time', models.DateTimeField(auto_now_add=True)),
                ('stay_time', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_client', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='last_image',
            field=models.ImageField(blank=True, upload_to='last_images/'),
        ),
        migrations.CreateModel(
            name='EmployeeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_enter_time', models.DateTimeField(auto_now_add=True)),
                ('last_leave_time', models.DateTimeField(auto_now_add=True)),
                ('stay_time', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_client', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.employee')),
            ],
            options={
                'db_table': 'employee_time',
            },
        ),
    ]
